# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rvncerr/u8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rvncerr/u8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rvncerr/u8/CMakeFiles /home/rvncerr/u8/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rvncerr/u8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named u8_cunit

# Build rule for target.
u8_cunit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u8_cunit
.PHONY : u8_cunit

# fast build rule for target.
u8_cunit/fast:
	$(MAKE) -f CMakeFiles/u8_cunit.dir/build.make CMakeFiles/u8_cunit.dir/build
.PHONY : u8_cunit/fast

#=============================================================================
# Target rules for targets named u8_static

# Build rule for target.
u8_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u8_static
.PHONY : u8_static

# fast build rule for target.
u8_static/fast:
	$(MAKE) -f CMakeFiles/u8_static.dir/build.make CMakeFiles/u8_static.dir/build
.PHONY : u8_static/fast

#=============================================================================
# Target rules for targets named u8_shared

# Build rule for target.
u8_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u8_shared
.PHONY : u8_shared

# fast build rule for target.
u8_shared/fast:
	$(MAKE) -f CMakeFiles/u8_shared.dir/build.make CMakeFiles/u8_shared.dir/build
.PHONY : u8_shared/fast

#=============================================================================
# Target rules for targets named u8

# Build rule for target.
u8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u8
.PHONY : u8

# fast build rule for target.
u8/fast:
	$(MAKE) -f CMakeFiles/u8.dir/build.make CMakeFiles/u8.dir/build
.PHONY : u8/fast

u8.o: u8.c.o

.PHONY : u8.o

# target to build an object file
u8.c.o:
	$(MAKE) -f CMakeFiles/u8.dir/build.make CMakeFiles/u8.dir/u8.c.o
.PHONY : u8.c.o

u8.i: u8.c.i

.PHONY : u8.i

# target to preprocess a source file
u8.c.i:
	$(MAKE) -f CMakeFiles/u8.dir/build.make CMakeFiles/u8.dir/u8.c.i
.PHONY : u8.c.i

u8.s: u8.c.s

.PHONY : u8.s

# target to generate assembly for a file
u8.c.s:
	$(MAKE) -f CMakeFiles/u8.dir/build.make CMakeFiles/u8.dir/u8.c.s
.PHONY : u8.c.s

u8_cunit.o: u8_cunit.c.o

.PHONY : u8_cunit.o

# target to build an object file
u8_cunit.c.o:
	$(MAKE) -f CMakeFiles/u8_cunit.dir/build.make CMakeFiles/u8_cunit.dir/u8_cunit.c.o
.PHONY : u8_cunit.c.o

u8_cunit.i: u8_cunit.c.i

.PHONY : u8_cunit.i

# target to preprocess a source file
u8_cunit.c.i:
	$(MAKE) -f CMakeFiles/u8_cunit.dir/build.make CMakeFiles/u8_cunit.dir/u8_cunit.c.i
.PHONY : u8_cunit.c.i

u8_cunit.s: u8_cunit.c.s

.PHONY : u8_cunit.s

# target to generate assembly for a file
u8_cunit.c.s:
	$(MAKE) -f CMakeFiles/u8_cunit.dir/build.make CMakeFiles/u8_cunit.dir/u8_cunit.c.s
.PHONY : u8_cunit.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... u8_cunit"
	@echo "... edit_cache"
	@echo "... u8_static"
	@echo "... u8_shared"
	@echo "... u8"
	@echo "... u8.o"
	@echo "... u8.i"
	@echo "... u8.s"
	@echo "... u8_cunit.o"
	@echo "... u8_cunit.i"
	@echo "... u8_cunit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

